[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.11.1"
  NODE_ENV = "production"
  SKIP_DATABASE_CONNECTION = "true"
  DISABLE_API_ROUTES = "true"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"
