[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  SKIP_DATABASE_CONNECTION = "true"
  DISABLE_API_ROUTES = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
